AWSTemplateFormatVersion: "2010-09-09"
Description: Simple S3 Bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-simple-bucket-123456
      AccessControl: Private

Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
    Description: The name of the S3 bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
    
