AWSTemplateFormatVersion: '2010-09-09'
Description: Simple IAM Role Example

Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MySimpleRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource: "*"

Outputs:
  Description: Id of role named MySimpleRole
  Value: !Ref MyIAMRole
