AWSTemplateFormatVersion: '2010-09-09'
Description: Simple IAM Role Example

Resources:
  MyIamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref MyIamUsername
      LoginProfile:
        Password: '{{resolve:secretsmanager:MyUserPassword:SecretString:password}}'
        PasswordResetRequired: false

Parameters:
  MyIamUsername:
    Type: String
    Default: test-user-00
